# Projects CMakeLists.txt

# 示例应用
add_subdirectory(App_HelloWorld)

# Demo 项目
add_subdirectory(Demo/Display_Demo)
add_subdirectory(Demo/LVGL_Gesture_Progress_Bar)
add_subdirectory(Demo/Algorithm_Detection_Demo)
add_subdirectory(Demo/Algorithm_Tracking_Demo)
add_subdirectory(Demo/OV5640_I2C1_Init)
add_subdirectory(Demo/Mailbox_Test)
add_subdirectory(Demo/UART3_Echo)
add_subdirectory(Demo/UART3_Interrupt)
add_subdirectory(Demo/DMA_Interrupt)
add_subdirectory(Demo/DMA_Ram2Ram)
add_subdirectory(Demo/DMA_ScatterGather)
add_subdirectory(Demo/DMA_LLI_Big)
add_subdirectory(Demo/DMA_UART3_Rx)
add_subdirectory(Demo/DMA_UART3_Tx)
add_subdirectory(Demo/FreeRTOS_Shell)
add_subdirectory(Demo/W25Qxx_Test)
add_subdirectory(Demo/PSRAM_Test)
add_subdirectory(Demo/Face_Recognition_Demo)
add_subdirectory(Demo/UART_File_Transfer)
add_subdirectory(Demo/Touch_Test)
add_subdirectory(Demo/Audio_KWS_Demo)
add_subdirectory(Demo/Audio_Playback_Demo)