#ifndef CARD1_VIDEO_COMPAT_H
#define CARD1_VIDEO_COMPAT_H

/*
 * Compatibility macros for MM/OV5640 drivers when board headers
 * do not provide legacy video_config symbols expected by video.c.
 */

#ifndef BOARD_LCD_TYPE
#define BOARD_LCD_TYPE 0
#endif

#ifndef RD_SOURCE_FRAME_START_X
#define RD_SOURCE_FRAME_START_X (0)
#endif
#ifndef RD_SOURCE_FRAME_START_Y
#define RD_SOURCE_FRAME_START_Y (0)
#endif

#ifndef BINNING_SIZE
#define BINNING_SIZE (1)
#endif

#ifndef BINNING_IMAGE_WIDTH
#define BINNING_IMAGE_WIDTH (288)
#endif
#ifndef BINNING_IMAGE_HEIGHT
#define BINNING_IMAGE_HEIGHT (360)
#endif

#ifndef SENSOR_IMAGE_WIDTH
#define SENSOR_IMAGE_WIDTH (BINNING_IMAGE_WIDTH * (1U << BINNING_SIZE))
#endif
#ifndef SENSOR_IMAGE_HEIGHT
#define SENSOR_IMAGE_HEIGHT (BINNING_IMAGE_HEIGHT * (1U << BINNING_SIZE))
#endif

#ifndef DOWNSCALE_IMAGE_WIDTH
#define DOWNSCALE_IMAGE_WIDTH (240)
#endif
#ifndef DOWNSCALE_IMAGE_HEIGHT
#define DOWNSCALE_IMAGE_HEIGHT (320)
#endif

#ifndef DISP_START_X
#define DISP_START_X (0)
#endif
#ifndef DISP_START_Y
#define DISP_START_Y (0)
#endif

#ifndef DISP_IMAGE_WIDTH
#define DISP_IMAGE_WIDTH (240)
#endif
#ifndef DISP_IMAGE_HEIGHT
#define DISP_IMAGE_HEIGHT (320)
#endif

#ifndef SNAP_IMAGE_WIDTH
#define SNAP_IMAGE_WIDTH (240)
#endif
#ifndef SNAP_IMAGE_HEIGHT
#define SNAP_IMAGE_HEIGHT (320)
#endif

#ifndef BINNING_LINE_MAX_SIZE
#define BINNING_LINE_MAX_SIZE (1280)
#endif
#ifndef DOWNSCALE_FACTOR
#define DOWNSCALE_FACTOR (8192)
#endif

#ifndef DISP_RALPHA0_ADDR
#define DISP_RALPHA0_ADDR (0x80700000 - (DISP_IMAGE_WIDTH * DISP_IMAGE_HEIGHT * 1))
#endif
#ifndef DISP_RALPHA1_ADDR
#define DISP_RALPHA1_ADDR (0x80700000 - (DISP_IMAGE_WIDTH * DISP_IMAGE_HEIGHT * 2))
#endif
#ifndef DISP_RFRAME0_ADDR
#define DISP_RFRAME0_ADDR (0x80700000 - (SNAP_IMAGE_WIDTH * SNAP_IMAGE_HEIGHT * 4))
#endif
#ifndef DISP_RFRAME1_ADDR
#define DISP_RFRAME1_ADDR (0x80700000 - (SNAP_IMAGE_WIDTH * SNAP_IMAGE_HEIGHT * 6))
#endif
#ifndef DISP_WFRAME0_ADDR
#define DISP_WFRAME0_ADDR (0x80700000 - (SNAP_IMAGE_WIDTH * SNAP_IMAGE_HEIGHT * 8))
#endif
#ifndef DISP_WFRAME1_ADDR
#define DISP_WFRAME1_ADDR (0x80700000 - (SNAP_IMAGE_WIDTH * SNAP_IMAGE_HEIGHT * 10))
#endif

#endif /* CARD1_VIDEO_COMPAT_H */
