#ifndef SUBBOARD_STARTUP_PROTO_H
#define SUBBOARD_STARTUP_PROTO_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define SUBBOARD_STARTUP_PROTO_VER            0x02u

#define SUBBOARD_STARTUP_SLAVE_ADDR_CARD1     0x10u
#define SUBBOARD_STARTUP_SLAVE_ADDR_CARD2     0x11u
#define SUBBOARD_STARTUP_SLAVE_ADDR_CARD3     0x12u

#define SUBBOARD_STARTUP_REG_STATUS           0x00u
#define SUBBOARD_STARTUP_REG_SYS_STATE        0x01u
#define SUBBOARD_STARTUP_REG_ERROR_CODE       0x02u
#define SUBBOARD_STARTUP_REG_HEARTBEAT        0x03u
#define SUBBOARD_STARTUP_REG_PROTO_VER        0x04u
#define SUBBOARD_STARTUP_REG_REQUEST          0x05u
#define SUBBOARD_STARTUP_REG_REQUEST_ARG      0x06u
#define SUBBOARD_STARTUP_REG_REQUEST_ACK      0x07u
#define SUBBOARD_STARTUP_REG_RESULT           0x10u
#define SUBBOARD_STARTUP_REG_CMD              0x80u
#define SUBBOARD_STARTUP_REG_CMD_ARG          0x81u
#define SUBBOARD_STARTUP_REG_CMD_ACK          0x82u
#define SUBBOARD_STARTUP_REG_CMD_RESULT       0x83u

#define SUBBOARD_STARTUP_STATUS_NONE          0x00u

#define SUBBOARD_STARTUP_STATE_BOOT           0x00u
#define SUBBOARD_STARTUP_STATE_I2C_READY      0x01u
#define SUBBOARD_STARTUP_STATE_WAIT_VIDEO     0x02u
#define SUBBOARD_STARTUP_STATE_WAIT_MASTER_MM 0x03u
#define SUBBOARD_STARTUP_STATE_MM_READY       0x04u
#define SUBBOARD_STARTUP_STATE_DSP_STARTING   0x05u
#define SUBBOARD_STARTUP_STATE_DSP_READY      0x06u
#define SUBBOARD_STARTUP_STATE_RUNNING        0x07u
#define SUBBOARD_STARTUP_STATE_ERROR          0xFFu

/* 子板向主板暴露的反向请求：由子板 DSP/CM4 提出，主板轮询后执行。 */
#define SUBBOARD_STARTUP_REQ_NONE                 0x00u
#define SUBBOARD_STARTUP_REQ_MASTER_MM_ENABLE     0x20u
#define SUBBOARD_STARTUP_REQ_MASTER_MM_RUNTIME    0x21u
#define SUBBOARD_STARTUP_REQ_MASTER_SPI_SYNC      0x22u

#define SUBBOARD_STARTUP_CMD_NONE             0x00u
#define SUBBOARD_STARTUP_CMD_PREPARE_VIDEO    0x10u
#define SUBBOARD_STARTUP_CMD_START_DSP        0x11u
#define SUBBOARD_STARTUP_CMD_STOP_PIPELINE    0x12u
#define SUBBOARD_STARTUP_CMD_CLEAR_ERROR      0x13u
#define SUBBOARD_STARTUP_CMD_PING             0x14u

#define SUBBOARD_STARTUP_RESULT_OK            0x00u
#define SUBBOARD_STARTUP_RESULT_BUSY          0x01u
#define SUBBOARD_STARTUP_RESULT_INVALID_STATE 0x02u
#define SUBBOARD_STARTUP_RESULT_MM_FAILED     0x03u
#define SUBBOARD_STARTUP_RESULT_DSP_FAILED    0x04u
#define SUBBOARD_STARTUP_RESULT_TIMEOUT       0x05u
#define SUBBOARD_STARTUP_RESULT_NOT_SUPPORTED 0x06u

#define SUBBOARD_STARTUP_ERR_NONE             0x00u
#define SUBBOARD_STARTUP_ERR_MM_INIT_FAIL     0x01u
#define SUBBOARD_STARTUP_ERR_UNSUPPORTED_CMD  0x02u
#define SUBBOARD_STARTUP_ERR_DSP_START_FAIL   0x03u

/*
 * v2 语义说明：
 * 1. `CMD` 仍然表示主板 -> 子板的调度命令。
 * 2. `REQUEST` 表示子板 -> 主板的资源/使能请求，由主板轮询后处理。
 * 3. 对于跨板视频场景，子板 DSP 不能直接要求本地 CM4 立即启 MM；
 *    它应先通知子板 CM4，再由子板 CM4 通过 `REQUEST` 暴露给主板。
 * 4. 主板处理完成后，可通过 `REQUEST_ACK` 回显已消费的请求，随后再下发下一条 `CMD`。
 */

#ifdef __cplusplus
}
#endif

#endif /* SUBBOARD_STARTUP_PROTO_H */