#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#define APP_HEARTBEAT_TASK_STACK_WORDS      1024U
#define APP_HEARTBEAT_TASK_PRIORITY         (tskIDLE_PRIORITY + 1)
#define APP_HEARTBEAT_PERIOD_MS             1000U

#define APP_CMD_TASK_STACK_WORDS            256U
#define APP_CMD_TASK_PRIORITY               (tskIDLE_PRIORITY + 2)
#define APP_CMD_POLL_PERIOD_MS              20U
#define APP_CMD_BUFFER_LEN                  48U

#define APP_KWS_TASK_STACK_WORDS            256U
#define APP_KWS_TASK_PRIORITY               (tskIDLE_PRIORITY + 3)
#define APP_KWS_POLL_PERIOD_MS              50U
#define APP_KWS_EVENT_COOLDOWN_MS           1200U

#define APP_CARDBUS_TASK_STACK_WORDS        256U
#define APP_CARDBUS_TASK_PRIORITY           (tskIDLE_PRIORITY + 4)
#define APP_CARDBUS_POLL_PERIOD_MS          20U
#define APP_CARDBUS_LOST_TIMEOUT_MS         300U
#define APP_CARDBUS_GESTURE_COOLDOWN_MS     600U

#define APP_DISPLAY_INIT_ENABLE              1

#define APP_HEARTBEAT_WS2812_ENABLE         1
#define APP_HEARTBEAT_WS2812_CHAIN0_PIN     BOARD_RGB_DIN1_PIN
#define APP_HEARTBEAT_WS2812_CHAIN0_LEDS    5U
#define APP_HEARTBEAT_WS2812_CHAIN1_ENABLE  1
#define APP_HEARTBEAT_WS2812_CHAIN1_PIN     BOARD_RGB_DIN2_PIN
#define APP_HEARTBEAT_WS2812_CHAIN1_LEDS    5U

#define APP_HEARTBEAT_WS2812_BRIGHTNESS     32U
#define APP_HEARTBEAT_WS2812_STEP_MS        80U

#define APP_HEARTBEAT_WS2812_BREATHE_MIN    14U
#define APP_HEARTBEAT_WS2812_BREATHE_MAX    52U
#define APP_HEARTBEAT_WS2812_BREATHE_STEP   2U
#define APP_HEARTBEAT_WS2812_PHOTO_FLASH_TICKS       2U
#define APP_HEARTBEAT_WS2812_PHOTO_FLASH_BRIGHTNESS  72U
#define APP_HEARTBEAT_WS2812_RECORDING_BRIGHTNESS_HIGH  72U
#define APP_HEARTBEAT_WS2812_RECORDING_BRIGHTNESS_LOW   14U

#endif /* APP_CONFIG_H */
