function(make_restore_cmd image_file addr output_var)
    if(EXISTS "${image_file}")
        file(SIZE "${image_file}" file_size)
        file(TO_CMAKE_PATH "${image_file}" image_file_clean)

        if(file_size GREATER 0)
            set(${output_var} "restore ${image_file_clean} binary ${addr}" PARENT_SCOPE)
            message(STATUS "Face_Detection_State_Machine_Demo: DSP bin ${image_file_clean} -> ${addr}")
        else()
            set(${output_var} "# ${image_file_clean} is empty, skipping" PARENT_SCOPE)
            message(STATUS "Face_Detection_State_Machine_Demo: DSP bin ${image_file_clean} is empty, skipping")
        endif()
    else()
        file(TO_CMAKE_PATH "${image_file}" image_file_clean)
        set(${output_var} "# ${image_file_clean} not found" PARENT_SCOPE)
        message(STATUS "Face_Detection_State_Machine_Demo: DSP bin ${image_file_clean} not found")
    endif()
endfunction()

if(NOT DEFINED DSP_BIN_DIR)
    message(FATAL_ERROR "DSP_BIN_DIR is required")
endif()

if(NOT DEFINED TEMPLATE_FILE)
    message(FATAL_ERROR "TEMPLATE_FILE is required")
endif()

if(NOT DEFINED OUTPUT_FILE)
    message(FATAL_ERROR "OUTPUT_FILE is required")
endif()

make_restore_cmd("${DSP_BIN_DIR}/model_dtcm_boot.bin" "0x44800000" GDB_RESTORE_DTCM)
make_restore_cmd("${DSP_BIN_DIR}/model_ptcm_boot.bin" "0x44A00000" GDB_RESTORE_PTCM)
make_restore_cmd("${DSP_BIN_DIR}/model_sram0_boot.bin" "0x44000000" GDB_RESTORE_SRAM0)
make_restore_cmd("${DSP_BIN_DIR}/model_sram1_boot.bin" "0x44040000" GDB_RESTORE_SRAM1)
make_restore_cmd("${DSP_BIN_DIR}/model_psram_boot.bin" "0x80000000" GDB_RESTORE_PSRAM)

file(READ "${TEMPLATE_FILE}" GDB_TEMPLATE_CONTENT)
string(REPLACE "@GDB_RESTORE_DTCM@" "${GDB_RESTORE_DTCM}" GDB_TEMPLATE_CONTENT "${GDB_TEMPLATE_CONTENT}")
string(REPLACE "@GDB_RESTORE_PTCM@" "${GDB_RESTORE_PTCM}" GDB_TEMPLATE_CONTENT "${GDB_TEMPLATE_CONTENT}")
string(REPLACE "@GDB_RESTORE_SRAM0@" "${GDB_RESTORE_SRAM0}" GDB_TEMPLATE_CONTENT "${GDB_TEMPLATE_CONTENT}")
string(REPLACE "@GDB_RESTORE_SRAM1@" "${GDB_RESTORE_SRAM1}" GDB_TEMPLATE_CONTENT "${GDB_TEMPLATE_CONTENT}")
string(REPLACE "@GDB_RESTORE_PSRAM@" "${GDB_RESTORE_PSRAM}" GDB_TEMPLATE_CONTENT "${GDB_TEMPLATE_CONTENT}")
file(WRITE "${OUTPUT_FILE}" "${GDB_TEMPLATE_CONTENT}")