function(_s300_json_string_value JSON_TEXT JSON_KEY OUTPUT_VAR)
    string(REGEX MATCH "\"${JSON_KEY}\"[ \t\r\n]*:[ \t\r\n]*\"([^\"]*)\"" _match "${JSON_TEXT}")
    if(_match)
        set(${OUTPUT_VAR} "${CMAKE_MATCH_1}" PARENT_SCOPE)
    else()
        set(${OUTPUT_VAR} "Unknown" PARENT_SCOPE)
    endif()
endfunction()

function(s300_load_model_metadata MODEL_DIR PREFIX)
    set(${PREFIX}_DIR "${MODEL_DIR}" PARENT_SCOPE)
    set(${PREFIX}_HAS_INFO FALSE PARENT_SCOPE)
    set(${PREFIX}_NAME "Unknown" PARENT_SCOPE)
    set(${PREFIX}_ID "Unknown" PARENT_SCOPE)
    set(${PREFIX}_VERSION "Unknown" PARENT_SCOPE)
    set(${PREFIX}_DATE "Unknown" PARENT_SCOPE)

    set(_info_path "${MODEL_DIR}/model_info.json")
    if(NOT EXISTS "${_info_path}")
        return()
    endif()

    file(READ "${_info_path}" _info_text)
    _s300_json_string_value("${_info_text}" "name" _name)
    _s300_json_string_value("${_info_text}" "id" _id)
    _s300_json_string_value("${_info_text}" "version" _version)
    _s300_json_string_value("${_info_text}" "date" _date)

    set(${PREFIX}_HAS_INFO TRUE PARENT_SCOPE)
    set(${PREFIX}_NAME "${_name}" PARENT_SCOPE)
    set(${PREFIX}_ID "${_id}" PARENT_SCOPE)
    set(${PREFIX}_VERSION "${_version}" PARENT_SCOPE)
    set(${PREFIX}_DATE "${_date}" PARENT_SCOPE)
endfunction()